### POST login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "Username": "UnidadePaulista.petcare@email.com",
  "password": "12345678"
}

### POST user
POST http://localhost:8080/tutor
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Carlos Tutor",
  "email": "carlos.tutor@example.com",
  "telefone": "11999998888",
  "cpf": "11122233344"
}